language: shell
os: osx
osx_image: xcode10.1
before_script:
  - export PATH=$PWD/travis-scripts:$PATH
script:
  - ./install
  - bash -l -c "update-dotbot-lists"
  - bash -O extglob -c "shellcheck install bash_profile scripts/!(git-merge-pr|npm-version)"
  - bash -O extglob -c "shfmt -i 2 -sr -d install bash_profile scripts/!(git-merge-pr|npm-version)"
if: branch = personal/macos
