language: shell
os: osx
osx_image: xcode10.1
env:
  - SELECTED_FOLDER="~/.dotfiles" SELECTED_REPO="https://github.com/jarrodldavis/dotfiles.git"
before_script:
  - export PATH=$PWD/travis-scripts:$PATH
script:
  - bash -c "$(curl -fsSL https://github.com/jarrodldavis/dotfiles/raw/personal/macos/install/bootstrap)" # From README
  - ./install/core # Test reinstall
  - bash -l -c "update-dotbot-lists"
  - bash -O extglob -c "shellcheck install/!(conf.yaml) bash_profile scripts/!(git-merge-pr|npm-version|export-user-defaults)"
  - bash -O extglob -c "shfmt -i 2 -sr -d install/!(conf.yaml) bash_profile scripts/!(git-merge-pr|npm-version|export-user-defaults)"
if: branch = personal/macos
notifications:
  slack:
    secure: UU/SDhyjRM663gJFa/fo6EzmRKMIvvwcmjg+Am+Klkal1l59KuK3t7QTTLcenFzFHcleaxLOJeCB6aZJ2wrUao7qJ5v4IloGLE3OvgsvRJUfgpWDCsRMJvnIeg9DNSmI1neYr8qajkT4YLmVCml6bHGh9OFvLIpPY7fOF2vFwSFfEYyLLmL2fenuaEkOqVJ2D8i7YzDdzvZv25CFJvaSIM1rNV3xGB7VJzwBPSW2/Gg+oQP/xIkzWOTzw8f+ZX7ACrQ0aGGQvJjVzFG3aDUcqPe/vV8o7L8Y9dEvbwwQlzHT7f9eNuO5cV7sZjJqp9PPDlJm6Sq+SSMG/WLT/CLoXhYMFuOOa8b1mxko+U8dbQFeyhtIVKMSjcfkWJFv8Wal/V7aM/yodbL4bO8RJuvM1BOZBeV571NNoHMcCevOwOIZtyOqmY5F0Zx/ocw6D/289Q6Zal1oUNHP85wUWCjDsO15XQK427Bfcx4tLkwgNhaVHMW/u/1yQle9cQLNVq9+nsihRtAj/OfTABy1BOMTzfSlTTDwwqMj6p4B0cSyxLI4EFEtesiZe4jWFBOisG4CkolemP7td2bftuBvEwF6dv6Jy6X1IAodwLiG9BmchNuT1KA9IRjHU1vm7gOv73hD8fiN07WCmI+lueQ3plDkGYrg7QdyVse6upb/rHz7uRg=
