language: shell
os: osx
osx_image: xcode10.1
before_script:
  - mkdir travis-scripts
  - echo "#! /usr/bin/env bash" > travis-scripts/mas
  - echo "echo 'Mac App Store:' \$*" > travis-scripts/mas
  - chmod +x travis-scripts/mas
  - export PATH=$PWD/travis-scripts:$PATH
script:
  - ./install
  - bash -O extglob -c "shellcheck install bash_profile scripts/!(git-merge-pr|npm-version)"
  - bash -O extglob -c "shfmt -i 2 -d install bash_profile scripts/!(git-merge-pr|npm-version)"
if: branch = personal/macos
