name: Continuous Integration

on: [push]

jobs:
  lint:
    name: Lint Shell Scripts
    runs-on: macOS-10.14
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Linters
        run: brew install shellcheck shfmt
      - name: shellcheck
        run: shellcheck install/bootstrap install/core ./bash* ./scripts/bash/*
      - name: shfmt
        run: shfmt -i 2 -sr -d install/bootstrap install/core ./bash* ./scripts/bash/*
