name: Continuous Integration

on: [push]

jobs:
  lint:
    name: Lint Shell Scripts
    runs-on: macOS-10.14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Install linters
        run: brew install shellcheck shfmt
      - name: Run shellcheck
        run: shellcheck install/bootstrap install/core ./bash* ./scripts/bash/*
      - name: Run shfmt
        run: shfmt -i 2 -sr -d install/bootstrap install/core ./bash* ./scripts/bash/*
  bootstrap:
    name: Test Automatic Bootstrapping
    runs-on: macOS-10.14
    steps:
      - name: Reset Homebrew environment
        run: |
          brew untap caskroom/versions
          brew uninstall node@6
      - name: Run bootstrapper
        env:
          BOOTSTRAP_URL: https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/install/core
          SELECTED_FOLDER: ~/.dotfiles
          SELECTED_REPO: ${{ github.repositoryUrl }}
          SKIP_SHELL_EXIT: 1
          PYTHONUNBUFFERED: 1
        run: |
          export PATH=$HOME/.dotfiles/.github/shims:$PATH
          bash -c "$(curl -fsSL $BOOTSTRAP_URL)"
install:
    name: Test Core Installer
    runs-on: macOS-10.14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Reset Homebrew environment
        run: |
          brew untap caskroom/versions
          brew uninstall node@6
      - name: Run installer
        env:
          SKIP_SHELL_EXIT: 1
          PYTHONUNBUFFERED: 1
        run: |
          export PATH=$GITHUB_WORKSPACE/.github/shims:$PATH
          ./install/core
      - name: Run installer again
        env:
          SKIP_SHELL_EXIT: 1
          PYTHONUNBUFFERED: 1
        run: |
          export PATH=$GITHUB_WORKSPACE/.github/shims:$PATH
          ./install/core
