name: Continuous Integration

on: [push]

SHELL_LINT_FILES: &SHELL_LINT_FILES
  env:
    SHELL_LINT_FILES: "install/bootstrap install/core bash_profile scripts/bash/*"

jobs:
  lint:
    runs-on: macOS-10.14
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Linters
        run: brew install shellcheck shfmt
      - name: shellcheck
        run: shellcheck $SHELL_LINT_FILES
        <<: *SHELL_LINT_FILES
      - name: shfmt
        run: shfmt -i 2 -sr -d $SHELL_LINT_FILES
        <<: *SHELL_LINT_FILES
