# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-13"]
        xcode: ["xcode_15.0"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode version
        run: sudo xcode-select --switch "/Applications/${{ matrix.xcode }}.app"
      - name: Update sudo config
        # Don't require password for `sudo -v`
        # https://askubuntu.com/a/1211226/9812
        run: sudo sh -c 'echo "Defaults verifypw = any" >> /etc/sudoers.d/verifypw'
      - name: Build
        run: swift build ${{ runner.debug && '-v' }}
      - name: Run
        run: swift run ${{ runner.debug && '-v' }} DotFiles ${{ runner.debug && '-vv' }}
