name: Installers

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  bootstrap:
    name: Bootstrap
    runs-on: macOS-10.14
    steps:
      - name: Reset Homebrew environment
        run: |
          brew uninstall node@6
          brew update-reset
      - name: Run bootstrapper
        env:
          BOOTSTRAP_URL: https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/install/bootstrap
          SELECTED_FOLDER: ~/.dotfiles
          SELECTED_REPO: ${{ github.repositoryUrl }}
          SKIP_SHELL_EXIT: 1
          PYTHONUNBUFFERED: 1
          CI: true
        run: |
          export PATH=$HOME/.dotfiles/.github/shims:$PATH
          bash -c "$(curl -fsSL $BOOTSTRAP_URL)"
  install:
    name: Core
    runs-on: macOS-10.14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Reset Homebrew environment
        run: |
          brew uninstall node@6
          brew update-reset
      - name: Run installer
        env:
          SKIP_SHELL_EXIT: 1
          PYTHONUNBUFFERED: 1
          CI: true
        run: |
          export PATH=$GITHUB_WORKSPACE/.github/shims:$PATH
          ./install/core
      - name: Run installer again
        env:
          SKIP_SHELL_EXIT: 1
          PYTHONUNBUFFERED: 1
          CI: true
        run: |
          export PATH=$GITHUB_WORKSPACE/.github/shims:$PATH
          ./install/core
